/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ExternalBlob = Uint8Array;
export interface LevelStage {
  'requiredCoins' : bigint,
  'displayText' : string,
  'rank' : string,
  'level' : bigint,
}
export interface LevelStatus {
  'nextStage' : LevelStage,
  'hasEnoughCoins' : boolean,
  'currentStage' : LevelStage,
  'userCoins' : bigint,
}
export interface Note {
  'id' : bigint,
  'title' : string,
  'content' : string,
  'subject' : string,
  'imageUrls' : Array<ExternalBlob>,
  'modifiedAt' : Time,
  'createdAt' : Time,
  'voiceNoteUrls' : Array<ExternalBlob>,
}
export interface PersistentFocusTimer {
  'isActive' : boolean,
  'remainingMinutes' : bigint,
}
export interface PersistentStopwatch {
  'startTime' : Time,
  'accumulatedTime' : bigint,
  'isRunning' : boolean,
}
export interface Reminder {
  'id' : bigint,
  'title' : string,
  'createdAt' : Time,
  'reminderTime' : bigint,
}
export interface Task {
  'id' : bigint,
  'title' : string,
  'subject' : string,
  'createdAt' : Time,
  'completed' : boolean,
  'description' : string,
  'priority' : bigint,
}
export type Time = bigint;
export interface TimerSessionV2 {
  'endTime' : bigint,
  'createdAt' : Time,
  'completed' : boolean,
  'durationMinutes' : bigint,
  'sessionId' : bigint,
  'isBackground' : boolean,
}
export interface TimetableEntry {
  'id' : bigint,
  'startTime' : bigint,
  'title' : string,
  'activityType' : string,
  'colorCode' : string,
  'endTime' : bigint,
  'createdAt' : Time,
}
export interface TimetableTick { 'entryId' : bigint, 'timestamp' : bigint }
export interface UserProfile {
  'bio' : string,
  'profileImage' : [] | [ExternalBlob],
  'name' : string,
  'coins' : bigint,
  'finishedSetup' : boolean,
  'nameChangeCount' : bigint,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addNote' : ActorMethod<[string, string, string], bigint>,
  'addNoteImage' : ActorMethod<[bigint, ExternalBlob], undefined>,
  'addReminder' : ActorMethod<[string, bigint], bigint>,
  'addTask' : ActorMethod<[string, string, string, bigint], bigint>,
  'addTimetableEntry' : ActorMethod<
    [string, string, bigint, bigint, string],
    bigint
  >,
  'addVoiceNote' : ActorMethod<[bigint, ExternalBlob], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'changeDisplayName' : ActorMethod<[string], undefined>,
  'clearFocusTimer' : ActorMethod<[], undefined>,
  'completeStopwatchSession' : ActorMethod<[bigint], boolean>,
  'completeTask' : ActorMethod<[bigint], undefined>,
  'deleteNote' : ActorMethod<[bigint], undefined>,
  'deleteReminder' : ActorMethod<[bigint], undefined>,
  'deleteTask' : ActorMethod<[bigint], undefined>,
  'deleteTimetableEntry' : ActorMethod<[bigint], undefined>,
  'getAllNotes' : ActorMethod<[], Array<Note>>,
  'getAllTasks' : ActorMethod<[], Array<Task>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCoinBalance' : ActorMethod<[], bigint>,
  'getCurrentAndNextLevelStage' : ActorMethod<[], LevelStatus>,
  'getFocusTimerState' : ActorMethod<[], [] | [PersistentFocusTimer]>,
  'getFullPersistentStopwatchState' : ActorMethod<[], [boolean, bigint]>,
  'getNewUserNeedsOnboarding' : ActorMethod<[], boolean>,
  'getPersistentStopwatchElapsedTime' : ActorMethod<[], bigint>,
  'getPersistentStopwatchState' : ActorMethod<[], [] | [PersistentStopwatch]>,
  'getStudyStreak' : ActorMethod<[], bigint>,
  'getTimerSessions' : ActorMethod<[], Array<TimerSessionV2>>,
  'getTimetableEntries' : ActorMethod<[], Array<TimetableEntry>>,
  'getTimetableTickHistoryForEntry' : ActorMethod<
    [bigint],
    Array<TimetableTick>
  >,
  'getTimetableTickStatsForEntry' : ActorMethod<
    [bigint],
    [bigint, Array<bigint>]
  >,
  'getTodayStopwatchRewardCount' : ActorMethod<[], bigint>,
  'getUpcomingReminders' : ActorMethod<[bigint], Array<Reminder>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'initializeProfile' : ActorMethod<[string, string], undefined>,
  'isBackgroundOwned' : ActorMethod<[string], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'markProfileSetupFinished' : ActorMethod<[], undefined>,
  'pausePersistentStopwatch' : ActorMethod<[], undefined>,
  'purchaseCustomBackground' : ActorMethod<[string], boolean>,
  'purchaseNextLevelStage' : ActorMethod<[], LevelStatus>,
  'recordTimerSession' : ActorMethod<[bigint, boolean], bigint>,
  'removeNoteImage' : ActorMethod<[bigint, ExternalBlob], undefined>,
  'removeVoiceNote' : ActorMethod<[bigint, ExternalBlob], undefined>,
  'resetPersistentStopwatch' : ActorMethod<[], undefined>,
  'resumePersistentStopwatch' : ActorMethod<[], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchNotes' : ActorMethod<[string], Array<Note>>,
  'spendCoinsForBackground' : ActorMethod<[string], boolean>,
  'startBackgroundFocusTimer' : ActorMethod<[bigint], undefined>,
  'startPersistentStopwatch' : ActorMethod<[], undefined>,
  'toggleTimetableEntryForToday' : ActorMethod<[bigint], boolean>,
  'updateCallerProfile' : ActorMethod<[[] | [ExternalBlob], string], undefined>,
  'updateFocusTimerState' : ActorMethod<[bigint, boolean], undefined>,
  'updateNote' : ActorMethod<
    [bigint, string, string, Array<ExternalBlob>, Array<ExternalBlob>],
    undefined
  >,
  'updateTimetableEntry' : ActorMethod<
    [bigint, string, string, string],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];