/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const Note = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'subject' : IDL.Text,
  'imageUrls' : IDL.Vec(ExternalBlob),
  'modifiedAt' : Time,
  'createdAt' : Time,
  'voiceNoteUrls' : IDL.Vec(ExternalBlob),
});
export const Task = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'subject' : IDL.Text,
  'createdAt' : Time,
  'completed' : IDL.Bool,
  'description' : IDL.Text,
  'priority' : IDL.Nat,
});
export const UserProfile = IDL.Record({
  'bio' : IDL.Text,
  'profileImage' : IDL.Opt(ExternalBlob),
  'name' : IDL.Text,
  'coins' : IDL.Nat,
  'finishedSetup' : IDL.Bool,
  'nameChangeCount' : IDL.Nat,
});
export const LevelStage = IDL.Record({
  'requiredCoins' : IDL.Nat,
  'displayText' : IDL.Text,
  'rank' : IDL.Text,
  'level' : IDL.Nat,
});
export const LevelStatus = IDL.Record({
  'nextStage' : LevelStage,
  'hasEnoughCoins' : IDL.Bool,
  'currentStage' : LevelStage,
  'userCoins' : IDL.Nat,
});
export const PersistentFocusTimer = IDL.Record({
  'isActive' : IDL.Bool,
  'remainingMinutes' : IDL.Nat,
});
export const PersistentStopwatch = IDL.Record({
  'startTime' : Time,
  'accumulatedTime' : IDL.Nat,
  'isRunning' : IDL.Bool,
});
export const TimerSessionV2 = IDL.Record({
  'endTime' : IDL.Int,
  'createdAt' : Time,
  'completed' : IDL.Bool,
  'durationMinutes' : IDL.Nat,
  'sessionId' : IDL.Nat,
  'isBackground' : IDL.Bool,
});
export const TimetableEntry = IDL.Record({
  'id' : IDL.Nat,
  'startTime' : IDL.Int,
  'title' : IDL.Text,
  'activityType' : IDL.Text,
  'colorCode' : IDL.Text,
  'endTime' : IDL.Int,
  'createdAt' : Time,
});
export const TimetableTick = IDL.Record({
  'entryId' : IDL.Nat,
  'timestamp' : IDL.Int,
});
export const Reminder = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'createdAt' : Time,
  'reminderTime' : IDL.Int,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addNote' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
  'addNoteImage' : IDL.Func([IDL.Nat, ExternalBlob], [], []),
  'addReminder' : IDL.Func([IDL.Text, IDL.Int], [IDL.Nat], []),
  'addTask' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Nat], [IDL.Nat], []),
  'addTimetableEntry' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Int, IDL.Int, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'addVoiceNote' : IDL.Func([IDL.Nat, ExternalBlob], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'changeDisplayName' : IDL.Func([IDL.Text], [], []),
  'clearFocusTimer' : IDL.Func([], [], []),
  'completeStopwatchSession' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'completeTask' : IDL.Func([IDL.Nat], [], []),
  'deleteNote' : IDL.Func([IDL.Nat], [], []),
  'deleteReminder' : IDL.Func([IDL.Nat], [], []),
  'deleteTask' : IDL.Func([IDL.Nat], [], []),
  'deleteTimetableEntry' : IDL.Func([IDL.Nat], [], []),
  'getAllNotes' : IDL.Func([], [IDL.Vec(Note)], ['query']),
  'getAllTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCoinBalance' : IDL.Func([], [IDL.Nat], ['query']),
  'getCurrentAndNextLevelStage' : IDL.Func([], [LevelStatus], ['query']),
  'getFocusTimerState' : IDL.Func(
      [],
      [IDL.Opt(PersistentFocusTimer)],
      ['query'],
    ),
  'getFullPersistentStopwatchState' : IDL.Func(
      [],
      [IDL.Bool, IDL.Nat],
      ['query'],
    ),
  'getNewUserNeedsOnboarding' : IDL.Func([], [IDL.Bool], ['query']),
  'getPersistentStopwatchElapsedTime' : IDL.Func([], [IDL.Nat], ['query']),
  'getPersistentStopwatchState' : IDL.Func(
      [],
      [IDL.Opt(PersistentStopwatch)],
      ['query'],
    ),
  'getStudyStreak' : IDL.Func([], [IDL.Nat], ['query']),
  'getTimerSessions' : IDL.Func([], [IDL.Vec(TimerSessionV2)], ['query']),
  'getTimetableEntries' : IDL.Func([], [IDL.Vec(TimetableEntry)], ['query']),
  'getTimetableTickHistoryForEntry' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(TimetableTick)],
      ['query'],
    ),
  'getTimetableTickStatsForEntry' : IDL.Func(
      [IDL.Nat],
      [IDL.Nat, IDL.Vec(IDL.Nat)],
      [],
    ),
  'getTodayStopwatchRewardCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getUpcomingReminders' : IDL.Func([IDL.Int], [IDL.Vec(Reminder)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'initializeProfile' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'isBackgroundOwned' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'markProfileSetupFinished' : IDL.Func([], [], []),
  'pausePersistentStopwatch' : IDL.Func([], [], []),
  'purchaseCustomBackground' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'purchaseNextLevelStage' : IDL.Func([], [LevelStatus], []),
  'recordTimerSession' : IDL.Func([IDL.Nat, IDL.Bool], [IDL.Nat], []),
  'removeNoteImage' : IDL.Func([IDL.Nat, ExternalBlob], [], []),
  'removeVoiceNote' : IDL.Func([IDL.Nat, ExternalBlob], [], []),
  'resetPersistentStopwatch' : IDL.Func([], [], []),
  'resumePersistentStopwatch' : IDL.Func([], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchNotes' : IDL.Func([IDL.Text], [IDL.Vec(Note)], ['query']),
  'spendCoinsForBackground' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'startBackgroundFocusTimer' : IDL.Func([IDL.Nat], [], []),
  'startPersistentStopwatch' : IDL.Func([], [], []),
  'toggleTimetableEntryForToday' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'updateCallerProfile' : IDL.Func([IDL.Opt(ExternalBlob), IDL.Text], [], []),
  'updateFocusTimerState' : IDL.Func([IDL.Nat, IDL.Bool], [], []),
  'updateNote' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Vec(ExternalBlob),
        IDL.Vec(ExternalBlob),
      ],
      [],
      [],
    ),
  'updateTimetableEntry' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const Note = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'subject' : IDL.Text,
    'imageUrls' : IDL.Vec(ExternalBlob),
    'modifiedAt' : Time,
    'createdAt' : Time,
    'voiceNoteUrls' : IDL.Vec(ExternalBlob),
  });
  const Task = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'subject' : IDL.Text,
    'createdAt' : Time,
    'completed' : IDL.Bool,
    'description' : IDL.Text,
    'priority' : IDL.Nat,
  });
  const UserProfile = IDL.Record({
    'bio' : IDL.Text,
    'profileImage' : IDL.Opt(ExternalBlob),
    'name' : IDL.Text,
    'coins' : IDL.Nat,
    'finishedSetup' : IDL.Bool,
    'nameChangeCount' : IDL.Nat,
  });
  const LevelStage = IDL.Record({
    'requiredCoins' : IDL.Nat,
    'displayText' : IDL.Text,
    'rank' : IDL.Text,
    'level' : IDL.Nat,
  });
  const LevelStatus = IDL.Record({
    'nextStage' : LevelStage,
    'hasEnoughCoins' : IDL.Bool,
    'currentStage' : LevelStage,
    'userCoins' : IDL.Nat,
  });
  const PersistentFocusTimer = IDL.Record({
    'isActive' : IDL.Bool,
    'remainingMinutes' : IDL.Nat,
  });
  const PersistentStopwatch = IDL.Record({
    'startTime' : Time,
    'accumulatedTime' : IDL.Nat,
    'isRunning' : IDL.Bool,
  });
  const TimerSessionV2 = IDL.Record({
    'endTime' : IDL.Int,
    'createdAt' : Time,
    'completed' : IDL.Bool,
    'durationMinutes' : IDL.Nat,
    'sessionId' : IDL.Nat,
    'isBackground' : IDL.Bool,
  });
  const TimetableEntry = IDL.Record({
    'id' : IDL.Nat,
    'startTime' : IDL.Int,
    'title' : IDL.Text,
    'activityType' : IDL.Text,
    'colorCode' : IDL.Text,
    'endTime' : IDL.Int,
    'createdAt' : Time,
  });
  const TimetableTick = IDL.Record({
    'entryId' : IDL.Nat,
    'timestamp' : IDL.Int,
  });
  const Reminder = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'createdAt' : Time,
    'reminderTime' : IDL.Int,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addNote' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
    'addNoteImage' : IDL.Func([IDL.Nat, ExternalBlob], [], []),
    'addReminder' : IDL.Func([IDL.Text, IDL.Int], [IDL.Nat], []),
    'addTask' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
        [IDL.Nat],
        [],
      ),
    'addTimetableEntry' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Int, IDL.Int, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'addVoiceNote' : IDL.Func([IDL.Nat, ExternalBlob], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'changeDisplayName' : IDL.Func([IDL.Text], [], []),
    'clearFocusTimer' : IDL.Func([], [], []),
    'completeStopwatchSession' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'completeTask' : IDL.Func([IDL.Nat], [], []),
    'deleteNote' : IDL.Func([IDL.Nat], [], []),
    'deleteReminder' : IDL.Func([IDL.Nat], [], []),
    'deleteTask' : IDL.Func([IDL.Nat], [], []),
    'deleteTimetableEntry' : IDL.Func([IDL.Nat], [], []),
    'getAllNotes' : IDL.Func([], [IDL.Vec(Note)], ['query']),
    'getAllTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCoinBalance' : IDL.Func([], [IDL.Nat], ['query']),
    'getCurrentAndNextLevelStage' : IDL.Func([], [LevelStatus], ['query']),
    'getFocusTimerState' : IDL.Func(
        [],
        [IDL.Opt(PersistentFocusTimer)],
        ['query'],
      ),
    'getFullPersistentStopwatchState' : IDL.Func(
        [],
        [IDL.Bool, IDL.Nat],
        ['query'],
      ),
    'getNewUserNeedsOnboarding' : IDL.Func([], [IDL.Bool], ['query']),
    'getPersistentStopwatchElapsedTime' : IDL.Func([], [IDL.Nat], ['query']),
    'getPersistentStopwatchState' : IDL.Func(
        [],
        [IDL.Opt(PersistentStopwatch)],
        ['query'],
      ),
    'getStudyStreak' : IDL.Func([], [IDL.Nat], ['query']),
    'getTimerSessions' : IDL.Func([], [IDL.Vec(TimerSessionV2)], ['query']),
    'getTimetableEntries' : IDL.Func([], [IDL.Vec(TimetableEntry)], ['query']),
    'getTimetableTickHistoryForEntry' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(TimetableTick)],
        ['query'],
      ),
    'getTimetableTickStatsForEntry' : IDL.Func(
        [IDL.Nat],
        [IDL.Nat, IDL.Vec(IDL.Nat)],
        [],
      ),
    'getTodayStopwatchRewardCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getUpcomingReminders' : IDL.Func(
        [IDL.Int],
        [IDL.Vec(Reminder)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'initializeProfile' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'isBackgroundOwned' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'markProfileSetupFinished' : IDL.Func([], [], []),
    'pausePersistentStopwatch' : IDL.Func([], [], []),
    'purchaseCustomBackground' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'purchaseNextLevelStage' : IDL.Func([], [LevelStatus], []),
    'recordTimerSession' : IDL.Func([IDL.Nat, IDL.Bool], [IDL.Nat], []),
    'removeNoteImage' : IDL.Func([IDL.Nat, ExternalBlob], [], []),
    'removeVoiceNote' : IDL.Func([IDL.Nat, ExternalBlob], [], []),
    'resetPersistentStopwatch' : IDL.Func([], [], []),
    'resumePersistentStopwatch' : IDL.Func([], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchNotes' : IDL.Func([IDL.Text], [IDL.Vec(Note)], ['query']),
    'spendCoinsForBackground' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'startBackgroundFocusTimer' : IDL.Func([IDL.Nat], [], []),
    'startPersistentStopwatch' : IDL.Func([], [], []),
    'toggleTimetableEntryForToday' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'updateCallerProfile' : IDL.Func([IDL.Opt(ExternalBlob), IDL.Text], [], []),
    'updateFocusTimerState' : IDL.Func([IDL.Nat, IDL.Bool], [], []),
    'updateNote' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Vec(ExternalBlob),
          IDL.Vec(ExternalBlob),
        ],
        [],
        [],
      ),
    'updateTimetableEntry' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };